apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-randomizer
  labels:
    app: image-randomizer-label
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image-randomizer-label
  template: # Pod template
    metadata:
      labels: 
        app: image-randomizer-label
    spec:
      containers:
      - name: image-randomizer
        image: oklahoma3/image-randomizer
        imagePullPolicy: Always
        ports:
          - containerPort: 80
        volumeMounts:
        - name: image-randomizer-volume
          mountPath: /data/images
        resources:
          limits:
            memory: "128Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: "/hc/live"
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
          failureThreshold: 2
        readinessProbe:
          httpGet:
            path: "/hc/ready"
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
          failureThreshold: 2
      volumes:
        - name: image-randomizer-volume
          persistentVolumeClaim:
            claimName: image-randomizer-pvc