apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: image-randomizer-pvc
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 5Gi