apiVersion: v1
kind: Service
metadata:
  name: image-randomizer-nodeport
spec:
  type: NodePort
  selector:
    app:  image-randomizer-label
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31000